/* Generated by packages/character/scripts/generate-firmware-presets.ts. Do not edit. */
#include "rig_presets.h"

const char *const RIG_AFFECT_NAMES[RIG_AFFECT_COUNT] = {
  "neutral",
  "happy",
  "sad",
  "angry",
  "surprised",
  "curious",
  "confused",
  "sleepy",
  "excited",
  "concerned",
  "laughing",
  "thinking",
  "playful",
  "shy",
  "proud",
};

const float RIG_NEUTRAL[RIG_PARAM_COUNT] = {
  1.0f, /* eyeOpen */
  0.05f, /* eyeSquint */
  0.0f, /* pupilX */
  0.0f, /* pupilY */
  1.0f, /* pupilSize */
  0.0f, /* browHeight */
  0.0f, /* browAngle */
  0.0f, /* browAsym */
  0.25f, /* mouthCurve */
  0.0f, /* mouthOpen */
  1.0f, /* mouthWidth */
  0.0f, /* mouthRound */
  0.25f, /* cheek */
  0.0f, /* headTilt */
  0.0f, /* bounce */
  0.0f, /* squash */
  0.45f, /* armL */
  0.45f, /* armR */
  0.35f, /* bendL */
  0.35f, /* bendR */
  1.0f, /* reachL */
  1.0f, /* reachR */
  0.0f, /* lean */
  0.0f, /* tear */
  0.0f, /* handSpeed */
};

const float RIG_PRESET_DELTA[RIG_AFFECT_COUNT][RIG_PARAM_COUNT] = {
  /* neutral */
  { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
  /* happy */
  { 0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.25f, 0.0f, 0.0f, 0.75f, 0.38f, 0.08f, 0.0f, 0.45f, 0.0f, 0.0f, 0.0f, 1.4f, 1.4f, 0.15f, 0.15f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
  /* sad */
  { -0.22f, 0.0f, 0.0f, 0.45f, 0.0f, -0.05f, 0.95f, 0.0f, -1.1f, 0.0f, -0.22f, 0.0f, -0.15f, 0.1f, 0.0f, 0.0f, -0.39f, -0.39f, -0.6f, -0.6f, 0.0f, 0.0f, 0.16f, 1.0f, 0.0f },
  /* angry */
  { -0.15f, 0.25f, 0.0f, 0.0f, 0.0f, -0.5f, -1.0f, 0.0f, -0.85f, 0.15f, -0.05f, 0.0f, 0.65f, 0.0f, 0.0f, 0.0f, -1.01f, -1.01f, 0.8f, 0.8f, -0.22f, -0.22f, 0.0f, 0.0f, 0.0f },
  /* surprised */
  { 0.3f, -0.05f, 0.0f, 0.0f, -0.2f, 1.0f, 0.0f, 0.0f, 0.0f, 0.75f, -0.3f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, -2.75f, -2.75f, 0.25f, 0.25f, -0.4f, -0.4f, 0.0f, 0.0f, 0.0f },
  /* curious */
  { 0.12f, 0.0f, 0.0f, 0.0f, 0.1f, 0.4f, 0.0f, 0.7f, 0.1f, 0.12f, 0.0f, 0.4f, 0.0f, 0.16f, 0.0f, 0.0f, -1.01f, -1.57f, 0.8f, -0.85f, -0.22f, 0.0f, 0.0f, 0.0f, 0.0f },
  /* confused */
  { 0.0f, 0.0f, -0.3f, 0.0f, 0.0f, 0.0f, 0.35f, -0.8f, -0.5f, 0.0f, -0.25f, 0.0f, 0.0f, -0.18f, 0.0f, 0.0f, -0.15f, 2.5f, 0.0f, 0.75f, 0.0f, -0.15f, 0.0f, 0.0f, 0.0f },
  /* sleepy */
  { -0.7f, 0.1f, 0.0f, 0.3f, 0.0f, -0.25f, 0.0f, 0.0f, -0.15f, 0.0f, 0.0f, 0.0f, 0.0f, 0.12f, 0.0f, 0.0f, -0.35f, -0.35f, 0.0f, 0.0f, 0.0f, 0.0f, 0.08f, 0.0f, 0.0f },
  /* excited */
  { 0.18f, 0.1f, 0.0f, 0.0f, 0.2f, 0.65f, 0.0f, 0.0f, 0.75f, 0.6f, 0.15f, 0.0f, 0.7f, 0.0f, 0.0f, 0.0f, 2.15f, 2.15f, 0.35f, 0.35f, 0.0f, 0.0f, 0.0f, 0.0f, 2.5f },
  /* concerned */
  { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.2f, 0.75f, 0.0f, -0.6f, 0.0f, -0.2f, 0.0f, 0.0f, -0.08f, 0.0f, 0.0f, -1.35f, -1.35f, -0.75f, -0.75f, -0.28f, -0.28f, 0.0f, 0.0f, 0.0f },
  /* laughing */
  { -0.7f, 0.95f, 0.0f, 0.0f, 0.0f, 0.55f, 0.0f, 0.0f, 0.75f, 0.75f, 0.15f, 0.0f, 0.75f, 0.0f, 0.0f, 0.0f, 1.9f, 1.9f, 0.35f, 0.35f, -0.1f, -0.1f, 0.0f, 0.0f, 0.0f },
  /* thinking */
  { 0.0f, 0.0f, 0.5f, -0.6f, 0.0f, 0.0f, 0.0f, 0.5f, -0.15f, 0.0f, -0.3f, 0.0f, 0.0f, -0.1f, 0.0f, 0.0f, -1.01f, 2.25f, 0.8f, 0.55f, -0.22f, -0.15f, 0.0f, 0.0f, 1.0f },
  /* playful */
  { 0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.2f, 0.0f, 0.45f, 0.75f, 0.4f, 0.05f, 0.0f, 0.45f, -0.08f, 0.0f, 0.0f, -1.01f, 1.35f, 0.8f, -0.1f, -0.22f, 0.05f, 0.0f, 0.0f, 0.0f },
  /* shy */
  { 0.05f, 0.0f, 0.35f, -0.45f, 0.15f, 0.2f, 0.25f, 0.0f, 0.5f, 0.0f, -0.3f, 0.0f, 0.75f, 0.13f, 0.0f, 0.0f, -1.67f, -1.67f, -1.15f, -1.15f, -0.18f, -0.18f, 0.0f, 0.0f, 0.0f },
  /* proud */
  { 0.0f, 0.3f, 0.0f, 0.0f, 0.0f, 0.35f, 0.0f, 0.0f, 0.75f, 0.45f, 0.1f, 0.0f, 0.4f, -0.06f, 0.0f, 0.0f, 0.8f, 0.8f, 0.5f, 0.5f, -0.15f, -0.15f, 0.0f, 0.0f, 0.0f },
};

const float RIG_TUNING[RIG_PARAM_COUNT][2] = {
  { 260.0f, 0.75f }, /* eyeOpen */
  { 200.0f, 0.8f }, /* eyeSquint */
  { 520.0f, 0.82f }, /* pupilX */
  { 520.0f, 0.82f }, /* pupilY */
  { 90.0f, 0.8f }, /* pupilSize */
  { 190.0f, 0.62f }, /* browHeight */
  { 190.0f, 0.7f }, /* browAngle */
  { 150.0f, 0.7f }, /* browAsym */
  { 170.0f, 0.72f }, /* mouthCurve */
  { 900.0f, 0.78f }, /* mouthOpen */
  { 520.0f, 0.8f }, /* mouthWidth */
  { 600.0f, 0.8f }, /* mouthRound */
  { 40.0f, 1.0f }, /* cheek */
  { 70.0f, 0.5f }, /* headTilt */
  { 120.0f, 0.38f }, /* bounce */
  { 260.0f, 0.3f }, /* squash */
  { 95.0f, 0.5f }, /* armL */
  { 95.0f, 0.5f }, /* armR */
  { 110.0f, 0.55f }, /* bendL */
  { 110.0f, 0.55f }, /* bendR */
  { 120.0f, 0.6f }, /* reachL */
  { 120.0f, 0.6f }, /* reachR */
  { 60.0f, 0.6f }, /* lean */
  { 8.0f, 1.0f }, /* tear */
  { 12.0f, 1.0f }, /* handSpeed */
};
