// Emits her rig's data tables as C for the desk companion (firmware/desk-companion/core).
// The firmware renders the same character from the same numbers; this keeps them one source.
import { writeFileSync } from "node:fs";
import { Affect } from "@ms-minutes/protocol";
import { NEUTRAL, PARAM_KEYS, PRESETS, TUNING } from "../src/index.js";

const outDir = new URL("../../../firmware/desk-companion/components/core/", import.meta.url);

const upper = (key: string) => key.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
const num = (v: number) => (Number.isInteger(v) ? `${v}.0f` : `${v}f`);

export function firmwarePresetsHeader(): string {
  const params = PARAM_KEYS.map((k, i) => `  RIG_${upper(k)} = ${i},`).join("\n");
  const affects = Affect.options.map((a, i) => `  AFFECT_${a.toUpperCase()} = ${i},`).join("\n");
  return `/* Generated by packages/character/scripts/generate-firmware-presets.ts. Do not edit. */
#pragma once

#define RIG_PARAM_COUNT ${PARAM_KEYS.length}
#define RIG_AFFECT_COUNT ${Affect.options.length}

/* Her face as numbers (ARCHITECTURE §9.2), in the order of packages/character PARAM_KEYS. */
enum rig_param {
${params}
};

/* Emotions she can show, in the order of the protocol's Affect enum. */
enum rig_affect {
${affects}
};

extern const char *const RIG_AFFECT_NAMES[RIG_AFFECT_COUNT];
extern const float RIG_NEUTRAL[RIG_PARAM_COUNT];
/* preset − neutral per parameter; an emotion at intensity w adds w × delta (blendTargets). */
extern const float RIG_PRESET_DELTA[RIG_AFFECT_COUNT][RIG_PARAM_COUNT];
/* { stiffness, damping ratio } per parameter, from the rig's spring tuning. */
extern const float RIG_TUNING[RIG_PARAM_COUNT][2];
`;
}

export function firmwarePresetsSource(): string {
  const names = Affect.options.map((a) => `  "${a}",`).join("\n");
  const neutral = PARAM_KEYS.map((k) => `  ${num(NEUTRAL[k])}, /* ${k} */`).join("\n");
  const deltas = Affect.options
    .map((a) => {
      const row = PARAM_KEYS.map((k) => {
        const v = PRESETS[a][k];
        return num(v === undefined ? 0 : +(v - NEUTRAL[k]).toFixed(6));
      });
      return `  /* ${a} */\n  { ${row.join(", ")} },`;
    })
    .join("\n");
  const tuning = PARAM_KEYS.map((k) => {
    const [stiffness, ratio] = TUNING[k];
    return `  { ${num(stiffness)}, ${num(ratio)} }, /* ${k} */`;
  }).join("\n");
  return `/* Generated by packages/character/scripts/generate-firmware-presets.ts. Do not edit. */
#include "rig_presets.h"

const char *const RIG_AFFECT_NAMES[RIG_AFFECT_COUNT] = {
${names}
};

const float RIG_NEUTRAL[RIG_PARAM_COUNT] = {
${neutral}
};

const float RIG_PRESET_DELTA[RIG_AFFECT_COUNT][RIG_PARAM_COUNT] = {
${deltas}
};

const float RIG_TUNING[RIG_PARAM_COUNT][2] = {
${tuning}
};
`;
}

if (process.argv[1]?.endsWith("generate-firmware-presets.ts")) {
  const header = new URL("include/rig_presets.h", outDir);
  const source = new URL("rig_presets.c", outDir);
  writeFileSync(header, firmwarePresetsHeader());
  writeFileSync(source, firmwarePresetsSource());
  console.log(`wrote ${header.pathname}\nwrote ${source.pathname}`);
}
