/* Generated by packages/character/scripts/generate-firmware-presets.ts. Do not edit. */
#pragma once

#define RIG_PARAM_COUNT 25
#define RIG_AFFECT_COUNT 15

/* Her face as numbers (ARCHITECTURE §9.2), in the order of packages/character PARAM_KEYS. */
enum rig_param {
  RIG_EYE_OPEN = 0,
  RIG_EYE_SQUINT = 1,
  RIG_PUPIL_X = 2,
  RIG_PUPIL_Y = 3,
  RIG_PUPIL_SIZE = 4,
  RIG_BROW_HEIGHT = 5,
  RIG_BROW_ANGLE = 6,
  RIG_BROW_ASYM = 7,
  RIG_MOUTH_CURVE = 8,
  RIG_MOUTH_OPEN = 9,
  RIG_MOUTH_WIDTH = 10,
  RIG_MOUTH_ROUND = 11,
  RIG_CHEEK = 12,
  RIG_HEAD_TILT = 13,
  RIG_BOUNCE = 14,
  RIG_SQUASH = 15,
  RIG_ARM_L = 16,
  RIG_ARM_R = 17,
  RIG_BEND_L = 18,
  RIG_BEND_R = 19,
  RIG_REACH_L = 20,
  RIG_REACH_R = 21,
  RIG_LEAN = 22,
  RIG_TEAR = 23,
  RIG_HAND_SPEED = 24,
};

/* Emotions she can show, in the order of the protocol's Affect enum. */
enum rig_affect {
  AFFECT_NEUTRAL = 0,
  AFFECT_HAPPY = 1,
  AFFECT_SAD = 2,
  AFFECT_ANGRY = 3,
  AFFECT_SURPRISED = 4,
  AFFECT_CURIOUS = 5,
  AFFECT_CONFUSED = 6,
  AFFECT_SLEEPY = 7,
  AFFECT_EXCITED = 8,
  AFFECT_CONCERNED = 9,
  AFFECT_LAUGHING = 10,
  AFFECT_THINKING = 11,
  AFFECT_PLAYFUL = 12,
  AFFECT_SHY = 13,
  AFFECT_PROUD = 14,
};

extern const char *const RIG_AFFECT_NAMES[RIG_AFFECT_COUNT];
extern const float RIG_NEUTRAL[RIG_PARAM_COUNT];
/* preset − neutral per parameter; an emotion at intensity w adds w × delta (blendTargets). */
extern const float RIG_PRESET_DELTA[RIG_AFFECT_COUNT][RIG_PARAM_COUNT];
/* { stiffness, damping ratio } per parameter, from the rig's spring tuning. */
extern const float RIG_TUNING[RIG_PARAM_COUNT][2];
