import type { Affect } from "@ms-minutes/protocol";
import { NEUTRAL, PARAM_KEYS, type HandPose, type RigParams } from "./params.js";

/**
 * Arm angles are radians from hanging down: π/2 is straight out, π straight up,
 * and negative angles bring the hand across in front of her (to her cheeks, hips, chin).
 */
const HANDS_ON_HIPS = { arm: -0.56, bend: 1.15, reach: 0.78 };
const HANDS_ON_CHEEKS = { arm: -1.22, bend: -0.8, reach: 0.82 };

/** Each emotion is a set of target values. Anything unset stays neutral. */
export const PRESETS: Record<Affect, Partial<RigParams>> = {
  neutral: {},
  happy: {
    eyeSquint: 0.3,
    browHeight: 0.25,
    mouthCurve: 1,
    mouthWidth: 1.08,
    mouthOpen: 0.38,
    cheek: 0.7,
    armL: 1.85,
    armR: 1.85,
    bendL: 0.5,
    bendR: 0.5,
  },
  sad: {
    eyeOpen: 0.78,
    browAngle: 0.95,
    browHeight: -0.05,
    mouthCurve: -0.85,
    mouthWidth: 0.78,
    pupilY: 0.45,
    headTilt: 0.1,
    cheek: 0.1,
    armL: 0.06,
    armR: 0.06,
    bendL: -0.25,
    bendR: -0.25,
    lean: 0.16,
    tear: 1,
  },
  angry: {
    eyeOpen: 0.85,
    eyeSquint: 0.3,
    browAngle: -1,
    browHeight: -0.5,
    mouthCurve: -0.6,
    mouthOpen: 0.15,
    mouthWidth: 0.95,
    cheek: 0.9,
    armL: HANDS_ON_HIPS.arm,
    armR: HANDS_ON_HIPS.arm,
    bendL: HANDS_ON_HIPS.bend,
    bendR: HANDS_ON_HIPS.bend,
    reachL: HANDS_ON_HIPS.reach,
    reachR: HANDS_ON_HIPS.reach,
  },
  surprised: {
    eyeOpen: 1.3,
    eyeSquint: 0,
    browHeight: 1,
    mouthOpen: 0.75,
    mouthRound: 1,
    mouthWidth: 0.7,
    pupilSize: 0.8,
    armL: -2.3,
    armR: -2.3,
    bendL: 0.6,
    bendR: 0.6,
    reachL: 0.6,
    reachR: 0.6,
  },
  curious: {
    eyeOpen: 1.12,
    browHeight: 0.4,
    browAsym: 0.7,
    headTilt: 0.16,
    mouthCurve: 0.35,
    mouthRound: 0.4,
    mouthOpen: 0.12,
    pupilSize: 1.1,
    armL: HANDS_ON_HIPS.arm,
    bendL: HANDS_ON_HIPS.bend,
    reachL: HANDS_ON_HIPS.reach,
    armR: -1.12,
    bendR: -0.5,
    reachR: 1.0,
  },
  confused: {
    browAsym: -0.8,
    browAngle: 0.35,
    headTilt: -0.18,
    mouthCurve: -0.25,
    mouthWidth: 0.75,
    pupilX: -0.3,
    armL: 0.3,
    armR: 2.95,
    bendR: 1.1,
    reachR: 0.85,
  },
  sleepy: {
    eyeOpen: 0.3,
    eyeSquint: 0.15,
    browHeight: -0.25,
    mouthCurve: 0.1,
    headTilt: 0.12,
    pupilY: 0.3,
    armL: 0.1,
    armR: 0.1,
    lean: 0.08,
  },
  excited: {
    eyeOpen: 1.18,
    eyeSquint: 0.15,
    browHeight: 0.65,
    mouthCurve: 1,
    mouthOpen: 0.6,
    mouthWidth: 1.15,
    cheek: 0.95,
    pupilSize: 1.2,
    armL: 2.6,
    armR: 2.6,
    bendL: 0.7,
    bendR: 0.7,
    handSpeed: 2.5,
  },
  concerned: {
    browAngle: 0.75,
    browHeight: 0.2,
    mouthCurve: -0.35,
    mouthWidth: 0.8,
    headTilt: -0.08,
    armL: -0.9,
    armR: -0.9,
    bendL: -0.4,
    bendR: -0.4,
    reachL: 0.72,
    reachR: 0.72,
  },
  laughing: {
    eyeOpen: 0.3,
    eyeSquint: 1,
    browHeight: 0.55,
    mouthCurve: 1,
    mouthOpen: 0.75,
    mouthWidth: 1.15,
    cheek: 1,
    armL: 2.35,
    armR: 2.35,
    bendL: 0.7,
    bendR: 0.7,
    reachL: 0.9,
    reachR: 0.9,
  },
  thinking: {
    pupilX: 0.5,
    pupilY: -0.6,
    browAsym: 0.5,
    mouthCurve: 0.1,
    mouthWidth: 0.7,
    headTilt: -0.1,
    armL: HANDS_ON_HIPS.arm,
    bendL: HANDS_ON_HIPS.bend,
    reachL: HANDS_ON_HIPS.reach,
    armR: 2.7,
    bendR: 0.9,
    reachR: 0.85,
    handSpeed: 1,
  },
  playful: {
    eyeSquint: 0.3,
    browAsym: 0.45,
    browHeight: 0.2,
    mouthCurve: 1,
    mouthOpen: 0.4,
    mouthWidth: 1.05,
    cheek: 0.7,
    headTilt: -0.08,
    armL: HANDS_ON_HIPS.arm,
    bendL: HANDS_ON_HIPS.bend,
    reachL: HANDS_ON_HIPS.reach,
    armR: 1.8,
    bendR: 0.25,
    reachR: 1.05,
  },
  shy: {
    eyeOpen: 1.05,
    pupilX: 0.35,
    pupilY: -0.45,
    pupilSize: 1.15,
    browHeight: 0.2,
    browAngle: 0.25,
    mouthCurve: 0.75,
    mouthWidth: 0.7,
    cheek: 1,
    headTilt: 0.13,
    armL: HANDS_ON_CHEEKS.arm,
    armR: HANDS_ON_CHEEKS.arm,
    bendL: HANDS_ON_CHEEKS.bend,
    bendR: HANDS_ON_CHEEKS.bend,
    reachL: HANDS_ON_CHEEKS.reach,
    reachR: HANDS_ON_CHEEKS.reach,
  },
  proud: {
    eyeSquint: 0.35,
    browHeight: 0.35,
    mouthCurve: 1,
    mouthOpen: 0.45,
    mouthWidth: 1.1,
    cheek: 0.65,
    headTilt: -0.06,
    armL: 1.25,
    armR: 1.25,
    bendL: 0.85,
    bendR: 0.85,
    reachL: 0.85,
    reachR: 0.85,
  },
};

/** Glove shapes per emotion: [screen-left hand, screen-right hand]. */
export const HAND_POSES: Record<Affect, [HandPose, HandPose]> = {
  neutral: ["open", "open"],
  happy: ["open", "open"],
  sad: ["open", "open"],
  angry: ["fist", "fist"],
  surprised: ["open", "open"],
  curious: ["fist", "point"],
  confused: ["open", "open"],
  sleepy: ["open", "open"],
  excited: ["fist", "fist"],
  concerned: ["fist", "fist"],
  laughing: ["fist", "fist"],
  thinking: ["fist", "point"],
  playful: ["fist", "point"],
  shy: ["fist", "fist"],
  proud: ["thumb", "thumb"],
};

export type BlendEntry = { affect: Affect; weight: number };

/** Weighted mix of emotions: neutral + Σ weight × (preset − neutral). */
export function blendTargets(entries: BlendEntry[]): RigParams {
  const out: RigParams = { ...NEUTRAL };
  for (const { affect, weight } of entries) {
    const preset = PRESETS[affect];
    for (const key of PARAM_KEYS) {
      const value = preset[key];
      if (value !== undefined) out[key] += (value - NEUTRAL[key]) * weight;
    }
  }
  return out;
}
